# Generated by Django 3.1.1 on 2020-10-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArxivApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='downloads',
            field=models.ManyToManyField(blank=True, related_name='download_users', to='ArxivApp.Paper'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmark_users', to='ArxivApp.Paper'),
        ),
    ]
