# Generated by Django 3.1.1 on 2020-11-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArxivApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='category',
        ),
        migrations.AlterField(
            model_name='paper',
            name='subject_classification',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
