# Generated by Django 3.1.1 on 2020-11-19 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArxivApp', '0002_auto_20201117_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='downvotes',
            new_name='votes',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='upvotes',
        ),
    ]
