# Generated by Django 3.1.1 on 2020-11-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArxivApp', '0003_auto_20201119_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
